import { IFormField } from "@/models/FormConfig";
import {
  LOCATIONS,
  TREATMENTS,
  LEAD_SOURCES,
  SUB_DISPOSITIONS,
  TELECONSULTATION_SLOTS,
} from "./leadOptions";

export const DEFAULT_FORM_FIELDS: IFormField[] = [
  // ── Section 1: Lead Date, Contact & Caller ─────────────────────────────
  {
    id: "uniqueId",
    label: "Unique ID",
    type: "text",
    section: 1,
    order: 1,
    required: true,
    isSystem: true,
    readOnly: true,
    placeholder: "SC-1",
    enabled: true,
  },
  {
    id: "date",
    label: "Date (DD-MMM-YY)",
    type: "date",
    section: 1,
    order: 2,
    required: false,
    isSystem: true,
    enabled: true,
  },
  {
    id: "leadTimestamp",
    label: "Time Stamp (Real-Time)",
    type: "text",
    section: 1,
    order: 3,
    required: false,
    isSystem: true,
    readOnly: true,
    enabled: true,
  },
  {
    id: "mobileNumber",
    label: "Mobile Number (10 digits)",
    type: "tel",
    section: 1,
    order: 4,
    required: true,
    isSystem: true,
    placeholder: "e.g. 9876543210",
    enabled: true,
  },
  {
    id: "alternateNumber",
    label: "Alternate # (10 digits)",
    type: "tel",
    section: 1,
    order: 5,
    required: false,
    isSystem: true,
    placeholder: "e.g. 9876543211",
    enabled: true,
  },
  {
    id: "callerName",
    label: "Caller Name (Drop Down)",
    type: "select",
    section: 1,
    order: 6,
    required: false,
    isSystem: true,
    options: ["Self / Direct Call", "Front Desk"],
    enabled: true,
  },
  {
    id: "leadSource",
    label: "Lead Source (Drop Down)",
    type: "select",
    section: 1,
    order: 7,
    required: false,
    isSystem: true,
    options: [...LEAD_SOURCES],
    enabled: true,
  },
  {
    id: "referredBy",
    label: "Referred By (Free text)",
    type: "text",
    section: 1,
    order: 8,
    required: false,
    isSystem: true,
    enabled: true,
  },

  // ── Section 2: Patient & Family Profile ───────────────────────────────
  {
    id: "patientName",
    label: "Patient Name (Free text)",
    type: "text",
    section: 2,
    order: 1,
    required: true,
    isSystem: true,
    placeholder: "Enter patient full name",
    enabled: true,
  },
  {
    id: "patientAge",
    label: "Patient Age (2 Digits)",
    type: "number",
    section: 2,
    order: 2,
    required: false,
    isSystem: true,
    placeholder: "e.g. 32",
    enabled: true,
  },
  {
    id: "location",
    label: "Location (Drop Down)",
    type: "select",
    section: 2,
    order: 3,
    required: false,
    isSystem: true,
    options: [...LOCATIONS],
    enabled: true,
  },
  {
    id: "spouseName",
    label: "Spouse Name (Free text)",
    type: "text",
    section: 2,
    order: 4,
    required: false,
    isSystem: true,
    enabled: true,
  },
  {
    id: "spouseAge",
    label: "Spouse Age (2 Digits)",
    type: "number",
    section: 2,
    order: 5,
    required: false,
    isSystem: true,
    placeholder: "e.g. 35",
    enabled: true,
  },

  // ── Section 3: Clinical & Surgical Details ────────────────────────────
  {
    id: "lookingForTreatment",
    label: "Looking for Treatment",
    type: "select",
    section: 3,
    order: 1,
    required: false,
    isSystem: true,
    options: [...TREATMENTS],
    enabled: true,
  },
  {
    id: "treatmentRequirements",
    label: "Treatment Requirements (Free text)",
    type: "text",
    section: 3,
    order: 2,
    required: false,
    isSystem: true,
    enabled: true,
  },
  {
    id: "preConditions",
    label: "Pre Conditions (Free text)",
    type: "text",
    section: 3,
    order: 3,
    required: false,
    isSystem: true,
    enabled: true,
  },
  {
    id: "surgeryDetails",
    label: "Surgery Details (Free text)",
    type: "text",
    section: 3,
    order: 4,
    required: false,
    isSystem: true,
    enabled: true,
  },

  // ── Section 4: Follow Up, Disposition & Appointments ───────────────────
  {
    id: "followUpDate",
    label: "Follow Up Date (DD-MMM-YY)",
    type: "date",
    section: 4,
    order: 1,
    required: false,
    isSystem: true,
    enabled: true,
  },
  {
    id: "subDispositions",
    label: "Sub Dispositions (Drop Down)",
    type: "select",
    section: 4,
    order: 2,
    required: false,
    isSystem: true,
    options: [...SUB_DISPOSITIONS],
    enabled: true,
  },
  {
    id: "appointmentDate",
    label: "Appointment Date (DD-MMM-YY)",
    type: "date",
    section: 4,
    order: 3,
    required: false,
    isSystem: true,
    enabled: true,
  },
  {
    id: "appointmentMonth",
    label: "Appointment Month (MMM-YY)",
    type: "text",
    section: 4,
    order: 4,
    required: false,
    isSystem: true,
    readOnly: true,
    enabled: true,
  },
  {
    id: "teleconsultationSlot",
    label: "Teleconsultation Slot (Drop Down)",
    type: "select",
    section: 4,
    order: 5,
    required: false,
    isSystem: true,
    options: [...TELECONSULTATION_SLOTS],
    enabled: true,
  },
  {
    id: "consultationCharges",
    label: "Consultation Charges (Amount)",
    type: "text",
    section: 4,
    order: 6,
    required: false,
    isSystem: true,
    placeholder: "e.g. 500",
    enabled: true,
  },
  {
    id: "surgeryDate",
    label: "Surgery Date (DD-MMM-YY)",
    type: "date",
    section: 4,
    order: 7,
    required: false,
    isSystem: true,
    enabled: true,
  },
  {
    id: "surgeryCost",
    label: "Surgery Cost (Amount)",
    type: "text",
    section: 4,
    order: 8,
    required: false,
    isSystem: true,
    placeholder: "e.g. 45000",
    enabled: true,
  },
  {
    id: "surgeryPaymentReceived",
    label: "Surgery Payment Received",
    type: "select",
    section: 4,
    order: 9,
    required: false,
    isSystem: true,
    options: ["No", "Yes - Partial", "Yes - Full Paid", "Pending"],
    enabled: true,
  },
  {
    id: "notes",
    label: "Notes & Observations",
    type: "textarea",
    section: 4,
    order: 10,
    required: false,
    isSystem: true,
    placeholder: "Enter internal communication notes...",
    enabled: true,
  },
];
